### ISSUE TITLE
Missing return?

### ISSUE THREAD

**Issue by kjleahy** [erl-lehigh/PyTeLo#26]
I think there should be a `return` at the beginning of line 103 if `return_directed` is True. https://github.com/wasserfeder/python-stl/blob/d0c7c64f15217718b4bded38cf6a99963aeedf9c/stl/stl_distance.py#L103

**Comment by wasserfeder** [comment]
Solved in commit b1ee418b1d218dd2d0b93e490b686ef341ccb374
